In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime
import finplot as fplt

In [2]:
start = datetime.datetime(2010,1,1)
end = datetime.datetime(2011,1,1)

In [15]:
stock = 'aapl'
df = web.DataReader(stock,'yahoo',start,end)
# df = df.drop(['Open','High','Low','Volume','Adj Close'],axis=1)
# pd.set_option('display.max_columns', None)

In [16]:
df.to_csv(stock+'.csv')

                 High        Low       Open      Close     Volume  Adj Close
Date
2009-12-31   7.619643   7.520000   7.611786   7.526072  352410800   6.439648
2010-01-04   7.660714   7.585000   7.622500   7.643214  493729600   6.539882
2010-01-05   7.699643   7.616071   7.664286   7.656428  601904800   6.551187
2010-01-06   7.686786   7.526786   7.656428   7.534643  552160000   6.446983
2010-01-07   7.571429   7.466072   7.562500   7.520714  477131200   6.435065
...               ...        ...        ...        ...        ...        ...
2010-12-27  11.622857  11.482857  11.530357  11.595715  249816000   9.921821
2010-12-28  11.666429  11.609285  11.639643  11.623929  175924000   9.945959
2010-12-29  11.658929  11.610714  11.650714  11.617500  163139200   9.940461
2010-12-30  11.625357  11.537500  11.624286  11.559286  157494400   9.890651
2010-12-31  11.552857  11.475357  11.533929  11.520000  193508000   9.857034

[253 rows x 6 columns]

In [20]:
#4 indicator MACD, RSI, Stochastic, Adx
#MACD
df['EWMA-5'] = df['Close'].ewm(span=5).mean()
df['EWMA-12'] = df['Close'].ewm(span=12).mean()
df['EWMA-26'] = df['Close'].ewm(span=26).mean()
df['MACD'] = df['EWMA-12'] - df['EWMA-26']
df['SIGNAL LINE'] = df['MACD'].ewm(span=9).mean() 

#RSI
def computeRSI (data, time_window):
    diff = data.diff(1).dropna()        
    up_chg = 0 * diff
    down_chg = 0 * diff
    up_chg[diff > 0] = diff[ diff>0 ]
    down_chg[diff < 0] = diff[ diff < 0 ]
    up_chg_avg   = up_chg.ewm(com=time_window-1 , min_periods=time_window).mean()
    down_chg_avg = down_chg.ewm(com=time_window-1 , min_periods=time_window).mean()
    rs = abs(up_chg_avg/down_chg_avg)
    rsi = 100 - 100/(1+rs)
    return rsi
df['RSI-7'] = computeRSI(df['Close'],12)
df['RSI-14'] = computeRSI(df['Close'], 26)

#DMI
adxi = ADXIndicator(df['High'],df['Low'],df['Close'],14,False)
df['+DI'] = adxi.adx_pos()
df['-DI'] = adxi.adx_neg()
df['adx'] = adxi.adx()

#STOCHASTIC Slow-fast
# Fast Stochastic
low_min  = df['Low'].rolling( window = 9 ).min()
high_max = df['High'].rolling( window = 9 ).max()
df['%K'] = (100*(df['Close']-low_min)/(high_max-low_min))
df['%D']=df['%K'].ewm(span=5).mean() 

#SLOW stochastic
df['%Ks'] = df['%D']
df['%Ds']=df['%Ks'].ewm(span=5).mean() 

#Ichimoku
ichi = IchimokuIndicator(df['High'],df['Low'],n1=9,n2=26,n3=52,visual=True,fillna=True)
df['ichi_a'] = ichi.ichimoku_a()
df['ichi_b'] = ichi.ichimoku_b()
df['ichi_base'] = ichi.ichimoku_base_line()
df['ichi_con']=ichi.ichimoku_conversion_line()

df['70'] = 70
df['30'] = 30
df['80'] = 80
df['20'] = 20

NameError: name 'ADXIndicator' is not defined

In [8]:
symbol = stock
ax,ax2,ax3,ax4 = fplt.create_plot(symbol, rows=4)

#plot1 main
fplt.candlestick_ochl(df[['Open','Close','High','Low']],ax=ax)

fplt.show()